telegram:
  bot_token: "<token>"
  channel_id: 123
  admin_id: 123

redis:
  host: "localhost"
  port: 6379
  expiration: 2400

parser:
  urls: [
    "https://habr.com/ru/hub/go/top10/",
  ]
  version: 2
  timeout: 1
